name: Build WASM

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: src/main.c

      - name: Bundle chip.json
        run: sudo cp chip.json dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chip
          path: |
            dist/chip.json
            dist/chip.wasm

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: chip
          path: chip

      - name: Create chip.zip
        run: cd chip && zip -9 ../chip.zip chip.*

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chip.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
